import { iEntity } from "../crosscommon/iEntity";
import { Catalog } from "../crosscommon/entities/Catalog";
import { User } from "../crosscommon/entities/User";
import { Logger } from "../crosscommon/entities/Logger";
import { Task } from "../crosscommon/entities/Task";
import { TaskTimeTracking } from "../crosscommon/entities/TaskTimeTracking";
import { TaskSchedule } from "../crosscommon/entities/TaskSchedule";
import { Account } from "../crosscommon/entities/Account";
import { Category } from "../crosscommon/entities/Category";
import { Place } from "../crosscommon/entities/Place";
import { Movement } from "../crosscommon/entities/Movement";
import { Entry } from "../crosscommon/entities/Entry";
import { Balance } from "../crosscommon/entities/Balance";
import { Preset } from "../crosscommon/entities/Preset";
import { LastTime } from "../crosscommon/entities/LastTime";
import { LastTimeHistory } from "../crosscommon/entities/LastTimeHistory";
import { Multimedia } from "../crosscommon/entities/Multimedia";
import { MultimediaDet } from "../crosscommon/entities/MultimediaDet";
import { MultimediaView } from "../crosscommon/entities/MultimediaView";
import { Link } from "../crosscommon/entities/Link";
import { Activity } from "../crosscommon/entities/Activity";
import { Keyval } from "../crosscommon/entities/Keyval";
import { CarteraProvision } from "../crosscommon/entities/CarteraProvision";
import { CarteraPayment } from "../crosscommon/entities/CarteraPayment";
import { CarteraPayDet } from "../crosscommon/entities/CarteraPayDet";
import { CarteraUnit } from "../crosscommon/entities/CarteraUnit";
import { Timeline } from "../crosscommon/entities/Timeline";
import { Budget } from "../crosscommon/entities/Budget";
declare const _default: {
    entityNameModelMap: {
        Catalog: (d: any) => Catalog;
        User: (d: any) => User;
        Logger: (d: any) => Logger;
        Task: (d: any) => Task;
        TaskTimeTracking: (d: any) => TaskTimeTracking;
        TaskSchedule: (d: any) => TaskSchedule;
        Account: (d: any) => Account;
        Category: (d: any) => Category;
        Place: (d: any) => Place;
        Movement: (d: any) => Movement;
        Entry: (d: any) => Entry;
        Balance: (d: any) => Balance;
        Preset: (d: any) => Preset;
        Budget: (d: any) => Budget;
        LastTime: (d: any) => LastTime;
        LastTimeHistory: (d: any) => LastTimeHistory;
        Multimedia: (d: any) => Multimedia;
        MultimediaDet: (d: any) => MultimediaDet;
        MultimediaView: (d: any) => MultimediaView;
        Link: (d: any) => Link;
        Activity: (d: any) => Activity;
        Keyval: (d: any) => Keyval;
        CarteraProvision: (d: any) => CarteraProvision;
        CarteraPayment: (d: any) => CarteraPayment;
        CarteraPayDet: (d: any) => CarteraPayDet;
        CarteraUnit: (d: any) => CarteraUnit;
        Timeline: (d: any) => Timeline;
    };
    instantiateFromString: (entityName: string, data?: any, withNoMetadata?: boolean) => iEntity;
    parseIntoObjectTree: (rows: Array<any>, tree: {
        main: string;
        additional?: any;
    }) => void[];
};
export default _default;
//# sourceMappingURL=InstantiateModule.d.ts.map